### ISSUE TITLE
Add a specific task file like .travis.yml

### ISSUE THREAD

**Issue by madcato** [madcato/BenderButler#4]
Name it **.bender.yml**

When running `$ bender` without parameters and **.bender.yml** file exists, then is processed.

Sample:
```yml
install:
  - git clone http://github.com/madcato/benderbutler.git master
  - package build benderbutler

script:
  - benderbutler dataToProcess

deploy:
  - git add .
  - git commit -m 'process finished'
  - git push origin master
```

Phases and their order:

1. **before_install** To Install installiton requisites like git, pip, apt-get, etc
2. **install** To install project
3. **before_script** To setup your running enviroment
4. **script** Run main process
5. **after_success** / **after_failure** 
6. **after_script** Runs after main process

Include this into wiki or readme
